### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by ASIMWELA** [agatha-chituwa/World_newsArticles#8]
Load the image view of the image source url with a default image when the url is null. Create a horizontal bar that separates each article from another in your recycler view. The article row should be clearly visible. If done with this,,  Create a reading page that will open when a user clicks a single article. The activity should have all the content of the clicked news(Check this, some articles come with the content while aothers come with the link to the whole article, add your logic to check this)

**Comment by agatha-chituwa** [comment]
Done
